#!/usr/bin/env bash

unlink $1/counting_phrase
cd $1
ln -s counting_phrase_noun counting_phrase
cd -
ls -l $1

./app evaluate_labelers $1 cheating

./app evaluate_labelers $1 cosine zero_order none
./app evaluate_labelers $1 cosine zero_order log
./app evaluate_labelers $1 cosine zero_order sqrt
./app evaluate_labelers $1 cosine zero_order linear

./app evaluate_labelers $1 cosine frequency none
./app evaluate_labelers $1 cosine frequency log
./app evaluate_labelers $1 cosine frequency sqrt
./app evaluate_labelers $1 cosine frequency linear

./app evaluate_labelers $1 cosine tf_idf none
./app evaluate_labelers $1 cosine tf_idf log
./app evaluate_labelers $1 cosine tf_idf sqrt
./app evaluate_labelers $1 cosine tf_idf linear

./app evaluate_labelers $1 first_order

rm -rf $1/noun_phrase
mkdir $1/noun_phrase
mv $1/*.txt $1/noun_phrase/
unlink $1/counting_phrase
cd $1
ln -s counting_phrase_n_gram counting_phrase
cd -
ls -l $1

./app evaluate_labelers $1 cheating

./app evaluate_labelers $1 cosine zero_order none
./app evaluate_labelers $1 cosine zero_order log
./app evaluate_labelers $1 cosine zero_order sqrt
./app evaluate_labelers $1 cosine zero_order linear

./app evaluate_labelers $1 cosine frequency none
./app evaluate_labelers $1 cosine frequency log
./app evaluate_labelers $1 cosine frequency sqrt
./app evaluate_labelers $1 cosine frequency linear

./app evaluate_labelers $1 cosine tf_idf none
./app evaluate_labelers $1 cosine tf_idf log
./app evaluate_labelers $1 cosine tf_idf sqrt
./app evaluate_labelers $1 cosine tf_idf linear

./app evaluate_labelers $1 first_order

rm -rf $1/n_gram
mkdir $1/n_gram
mv $1/*.txt $1/n_gram/
unlink $1/counting_phrase