#!/bin/sh

bzcat data/long_abstracts_en.ttl.bz2 | ./app import long_abstracts db/full
bzcat data/labels_en.ttl.bz2 | ./app import article_titles db/full
bzcat data/redirects_transitive_en.ttl.bz2 | ./app import redirects_transitive db/full
bzcat data/category_labels_en.ttl.bz2 | ./app import category_labels db/full
bzcat data/article_categories_en.ttl.bz2 | ./app import article_categories db/full
bzcat data/skos_categories_en.ttl.bz2 | ./app import skos_categories db/full
