#!/bin/sh

bzcat long_abstracts_en.ttl.bz2 | ./app import long_abstracts db/ifull
bzcat labels_en.ttl.bz2 | ./app import article_titles db/ifull
bzcat redirects_transitive_en.ttl.bz2 | ./app import redirects_transitive db/ifull
bzcat category_labels_en.ttl.bz2 | ./app import category_labels db/ifull
bzcat article_categories_en.ttl.bz2 | ./app import article_categories db/ifull
bzcat skos_categories_en.ttl.bz2 | ./app import skos_categories db/ifull
